package project1;

import java.io.IOException;  
import java.io.PrintWriter;  
import javax.servlet.ServletException;  
import javax.servlet.annotation.WebServlet;  
import javax.servlet.http.HttpServlet;  
import javax.servlet.http.HttpServletRequest;  
import javax.servlet.http.HttpServletResponse;  

@WebServlet("/AS_EditServlet")  
public class AS_EditServlet extends HttpServlet {  
    protected void doGet(HttpServletRequest request, HttpServletResponse response)   
           throws ServletException, IOException {  
        response.setContentType("text/html");  
        PrintWriter out=response.getWriter();  
        
        String sid=request.getParameter("id");  
        int id=Integer.parseInt(sid);  
          
        AS_Activity e=AS_ActivityDAO.getActivityById(id);  
        out.print("<form action='AS_EditServlet2' method='Post'>");  
          
       out.print("<h1 style=\" text-shadow:2px 2px black;\"><b><span class=\"blue\"></span>Update<span class=\"blue\"></span> <span class=\"yellow\">AS_Activity</span></b></h1>\r\n"
       		+ "\r\n"
       		+ "<table class=\"container\">\r\n"
       		+ "	<thead>\r\n"
       		+ "		<tr>\r\n"
       		
       		+ "			<th><h1>Activity Name</h1></th>\r\n"
       		+ "			<th><h1>Student Name</h1></th>\r\n"
       		+ "			<th><h1>Student Email</h1></th>\r\n"
       		+ "			<th><h1>Group Name</h1></th>\r\n"
       		+ "		</tr>\r\n"
       		+ "	</thead>\r\n"
       		+ "	<tbody>\r\n"
       		+ "		<tr>\r\n"
       		
       		+ "			<td><select name='aname' value='"+e.getAname() +"' style='width:85% '>"
       		+ "							<option>Soccer</option>\r\n"
       		+ "							<option>Cricket</option>\r\n"
       		+ "							<option>Basketball</option>\r\n"
       		+ "							<option>Race 400m</option>"
       		+ "</select></td>\r\n"
       		
       		+ "<td><input type='text' name='sname' value='"+e.getSname()+"'/ style=\"color:black\";></td>"
       		+ "			<td><input type='email' name='semail' value='"+e.getSemail()+"'/ style=\"color:black\"></td>\r\n"
       		+ "			<td><select name='gname' value='"+e.getGname() +"' style='width:150px'>"
       				
       		+ "<option>CPCM Group 1</option>"
       		+ "<option>CPCM Group 2</option>"
       		+ "<option>CPCM Group 3</option>"
       		+ "<option>Other</option>"
       		+"<input type='hidden' name='id' value='"+e.getId()+"'/>"
       		+ "</td>\r\n"
       		+ "		</tr>\r\n"
       		+ "	</tbody>\r\n"
       		+ "</table>");
       out.print("<tr><td colspan='2' style=''><input type=\"submit\" value=\"Edit &amp; Save \" style=\"\r\n"
       		+ "    background-color: #0E1119;\r\n"
       		+ "    padding: 15px;\r\n"
       		+ "    margin-left: 50%;\r\n"
       		+ "    margin-top: -70px;\r\n"
       		+" color:white;\r\n"
       		+"font-size:20px;\r\n"
       		+ "\"></td></tr>"); 
       out.print("	<style> \r\n"
       		+ "\r\n"
       		+ "@charset \"UTF-8\";\r\n"
       		+ "@import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,700);\r\n"
       		+ "\r\n"
       		+ "body {\r\n"
       		+ "  font-family: 'Open Sans', sans-serif;\r\n"
       		+ "  font-weight: 300;\r\n"
       		+ "  line-height: 1.42em;\r\n"
       		+ "  color:#A7A1AE;\r\n"
       		+ "  background-image:url(\"2.jpg\");\r\n"
       		+"background-size:cover;"
       		+ "}\r\n"
       		+ "\r\n"
       		+ "h1 {\r\n"
       		+ "  font-size:3em; \r\n"
       		+ "  font-weight: 300;\r\n"
       		+ "  line-height:1em;\r\n"
       		+ "  text-align: center;\r\n"
       		+ "  color: #4DC3FA;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ "h2 {\r\n"
       		+ "  font-size:1em; \r\n"
       		+ "  font-weight: 300;\r\n"
       		+ "  text-align: center;\r\n"
       		+ "  display: block;\r\n"
       		+ "  line-height:1em;\r\n"
       		+ "  padding-bottom: 2em;\r\n"
       		+ "  color: #FB667A;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ "h2 a {\r\n"
       		+ "  font-weight: 700;\r\n"
       		+ "  text-transform: uppercase;\r\n"
       		+ "  color: #FB667A;\r\n"
       		+ "  text-decoration: none;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".blue { color: #185875; }\r\n"
       		+ ".yellow { color: #FFF842; }\r\n"
       		+ "\r\n"
       		+ ".container th h1 {\r\n"
       		+ "	  font-weight: bold;\r\n"
       		+ "	  font-size: 1em;\r\n"
       		+ "  text-align: left;\r\n"
       		+ "  color: #185875;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ " td {\r\n"
       		+ "	  font-weight: normal;\r\n"
       		+ "	  font-size: 1em;\r\n"
       		+ "  -webkit-box-shadow: 0 2px 2px -2px #0E1119;\r\n"
       		+ "	   -moz-box-shadow: 0 2px 2px -2px #0E1119;\r\n"
       		+ "	        box-shadow: 0 2px 2px -2px #0E1119;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".container {\r\n"
       		+ "	  text-align: left;\r\n"
       		+ "	  overflow: hidden;\r\n"
       		+ "	  width: 80%;\r\n"
       		+ "	  margin: 0 auto;\r\n"
       		+ "  display: table;\r\n"
       		+ "  padding: 0 0 8em 0;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".container td, .container th {\r\n"
       		+ "	  padding-bottom: 2%;\r\n"
       		+ "	  padding-top: 2%;\r\n"
       		+ "  padding-left:2%;  \r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ "/* Background-color of the odd rows */\r\n"
       		+ ".container tr:nth-child(odd) {\r\n"
       		+ "	  background-color: #323C50;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ "/* Background-color of the even rows */\r\n"
       		+ ".container tr:nth-child(even) {\r\n"
       		+ "	  background-color: #2C3446;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".container th {\r\n"
       		+ "	  background-color: #1F2739;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".container td:first-child { color: #FB667A; }\r\n"
       		+ "\r\n"
       		+ ".container tr:hover {\r\n"
       		+ "   background-color: #464A52;\r\n"
       		+ "-webkit-box-shadow: 0 6px 6px -6px #0E1119;\r\n"
       		+ "	   -moz-box-shadow: 0 6px 6px -6px #0E1119;\r\n"
       		+ "	        box-shadow: 0 6px 6px -6px #0E1119;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ ".container td:hover {\r\n"
       		+ "  background-color: #FFF842;\r\n"
       		+ "  color: #403E10;\r\n"
       		+ "  font-weight: bold;\r\n"
       		+ "  \r\n"
       		+ "  box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;\r\n"
       		+ "  transform: translate3d(6px, -6px, 0);\r\n"
       		+ "  \r\n"
       		+ "  transition-delay: 0s;\r\n"
       		+ "	  transition-duration: 0.4s;\r\n"
       		+ "	  transition-property: all;\r\n"
       		+ "  transition-timing-function: line;\r\n"
       		+ "}\r\n"
       		+ "\r\n"
       		+ "@media (max-width: 800px) {\r\n"
       		+ ".container td:nth-child(4),\r\n"
       		+ ".container th:nth-child(4) { display: none; }\r\n"
       		+ "} </style>");
          
        out.close();  
    }  
}  